import { create } from 'zustand';

export const PLANS = {
  spark: { id: 'spark', name: 'Spark', tagline: 'That first glow', icon: '✨', price: 'Free', color: '#f59e0b', features: ['Unlimited chat', '1 game per day', 'Basic voice calls', 'YouTube watch together', 'Daily prompts'] },
  embrace: { id: 'embrace', name: 'Embrace', tagline: 'Closer every day', icon: '💫', price: '₹499/mo', color: '#6c63ff', features: ['Unlimited chat', '3-4 games per day', 'HD voice & video calls', 'All platforms watch together', 'Daily prompts & mood tracking'] },
  eclipse: { id: 'eclipse', name: 'Eclipse', tagline: 'Two souls, one orbit', icon: '🌑', price: '₹999/mo', color: '#ec4899', features: ['Everything in Embrace, unlimited', 'All games — unlimited plays', 'Unlimited streaming — all platforms', 'Priority support', 'Custom themes & chat colors'] },
};

const useStore = create((set, get) => ({
  user: { name: 'Alex', avatar: null },
  partner: { name: 'Partner', avatar: null },
  partnerOnline: true,
  partnerActivity: 'Listening to music 🎵',
  plan: 'spark',
  showUpgradeBanner: true,
  callState: 'idle',
  callType: null,
  isMuted: false,
  isCameraOff: false,
  callDuration: 0,
  watchUrl: '',
  isPlaying: false,
  currentTime: 0,
  isPiPOpen: false,
  platform: null,
  isManualMode: false,
  manualTime: 0,
  partnerManualTime: null,
  partnerPlatform: null,
  currentMood: null,
  triviaState: null,
  truthOrDareState: null,
  wyrState: null,
  streak: 47,
  daysSinceStart: (() => Math.floor((Date.now() - new Date('2024-06-15').getTime()) / 86400000))(),
  messages: [
    { id: '1', text: "Hey! How's your day going?", sender: 'partner', time: '2:30 PM' },
    { id: '2', text: 'It was great! Miss you 🥰', sender: 'me', time: '2:31 PM' },
    { id: '3', text: 'Miss you too! Can\'t wait for the weekend', sender: 'partner', time: '2:32 PM' },
  ],

  setUser: (user) => set({ user }),
  setPartner: (partner) => set({ partner }),
  setPartnerOnline: (online) => set({ partnerOnline: online, partnerActivity: online ? 'Online' : 'Last seen 2h ago' }),
  setPlan: (plan) => set({ plan }),
  setShowUpgradeBanner: (show) => set({ showUpgradeBanner: show }),
  setCallState: (s) => set({ callState: s }),
  setCallType: (t) => set({ callType: t }),
  setIsMuted: (m) => set({ isMuted: m }),
  setIsCameraOff: (c) => set({ isCameraOff: c }),
  setCallDuration: (d) => set({ callDuration: d }),
  setWatchUrl: (u) => set({ watchUrl: u }),
  setIsPlaying: (p) => set({ isPlaying: p }),
  setCurrentTime: (t) => set({ currentTime: t }),
  setIsPiPOpen: (p) => set({ isPiPOpen: p }),
  setPlatform: (p) => set({ platform: p }),
  setIsManualMode: (m) => set({ isManualMode: m }),
  setManualTime: (t) => set({ manualTime: typeof t === 'function' ? t(get().manualTime) : t }),
  setPartnerManualTime: (t) => set({ partnerManualTime: t }),
  setPartnerPlatform: (p) => set({ partnerPlatform: p }),
  setCurrentMood: (m) => set({ currentMood: m }),
  setTriviaState: (s) => set({ triviaState: s }),
  setTruthOrDareState: (s) => set({ truthOrDareState: s }),
  setWyrState: (s) => set({ wyrState: s }),
  addMessage: (msg) => set((s) => ({ messages: [...s.messages, msg] })),
  resetCall: () => set({ callState: 'idle', callType: null, isMuted: false, isCameraOff: false, callDuration: 0 }),
}));

export default useStore;
